#!/bin/bash
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".

pushd ..
bin/console doc:mig:mig -n
sudo -u nginx /home/al/.local/bin/con cache:clear

pushd docs/
mdbook build
