<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260206093443 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create ConstructionImplementation entity (施工实施流程) and add relationships with File/Image entities';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE construction_implementation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date DATE DEFAULT NULL, completion_date DATE DEFAULT NULL, construction_progress_details TEXT DEFAULT NULL, quality_inspection_details TEXT DEFAULT NULL, safety_inspection_details TEXT DEFAULT NULL, progress_payment_details TEXT DEFAULT NULL, change_order_details TEXT DEFAULT NULL, supervision_details TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CF676D06166D1F9C ON construction_implementation (project_id)');
        $this->addSql('ALTER TABLE construction_implementation ADD CONSTRAINT FK_CF676D06166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE file ADD construction_implementation_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE file ADD CONSTRAINT FK_8C9F36106149585C FOREIGN KEY (construction_implementation_id) REFERENCES construction_implementation (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX idx_file_construction_implementation ON file (construction_implementation_id)');
        $this->addSql('ALTER TABLE image ADD construction_implementation_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE image ADD CONSTRAINT FK_C53D045F6149585C FOREIGN KEY (construction_implementation_id) REFERENCES construction_implementation (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX idx_image_construction_implementation ON image (construction_implementation_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE construction_implementation DROP CONSTRAINT FK_CF676D06166D1F9C');
        $this->addSql('DROP TABLE construction_implementation');
        $this->addSql('ALTER TABLE file DROP CONSTRAINT FK_8C9F36106149585C');
        $this->addSql('DROP INDEX idx_file_construction_implementation');
        $this->addSql('ALTER TABLE file DROP construction_implementation_id');
        $this->addSql('ALTER TABLE image DROP CONSTRAINT FK_C53D045F6149585C');
        $this->addSql('DROP INDEX idx_image_construction_implementation');
        $this->addSql('ALTER TABLE image DROP construction_implementation_id');
    }
}
