<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260716160000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add project_progress_report table and project.progress_report_interval_days';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE project ADD progress_report_interval_days INT DEFAULT NULL');

        $this->addSql('CREATE TABLE project_progress_report (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, period_start_date DATE NOT NULL, period_end_date DATE NOT NULL, progress_percentage INT NOT NULL, status_tag VARCHAR(255) NOT NULL, current_progress_summary TEXT NOT NULL, next_period_plan TEXT DEFAULT NULL, issues TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, reported_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4DF753A371CE806 ON project_progress_report (reported_by_id)');
        $this->addSql('CREATE INDEX idx_progress_report_project ON project_progress_report (project_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_progress_report_project_period ON project_progress_report (project_id, period_start_date)');
        $this->addSql('ALTER TABLE project_progress_report ADD CONSTRAINT FK_4DF753A3166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_progress_report ADD CONSTRAINT FK_4DF753A371CE806 FOREIGN KEY (reported_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE project_progress_report DROP CONSTRAINT FK_4DF753A3166D1F9C');
        $this->addSql('ALTER TABLE project_progress_report DROP CONSTRAINT FK_4DF753A371CE806');
        $this->addSql('DROP TABLE project_progress_report');

        $this->addSql('ALTER TABLE project DROP progress_report_interval_days');
    }
}
