<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260206095850 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE settlement_accounts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, settlement_date DATE DEFAULT NULL, contract_settlement_details TEXT DEFAULT NULL, cost_audit_details TEXT DEFAULT NULL, quantity_survey_details TEXT DEFAULT NULL, dispute_resolution_details TEXT DEFAULT NULL, payment_completion_details TEXT DEFAULT NULL, warranty_management_details TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_17D0AAA0166D1F9C ON settlement_accounts (project_id)');
        $this->addSql('CREATE INDEX idx_settlement_date ON settlement_accounts (settlement_date)');
        $this->addSql('CREATE INDEX idx_settlement_accounts_created_at ON settlement_accounts (created_at)');
        $this->addSql('ALTER TABLE settlement_accounts ADD CONSTRAINT FK_17D0AAA0166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE file ADD settlement_accounts_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE file ADD CONSTRAINT FK_8C9F36106D021EF0 FOREIGN KEY (settlement_accounts_id) REFERENCES settlement_accounts (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX idx_file_settlement_accounts ON file (settlement_accounts_id)');
        $this->addSql('ALTER TABLE image ADD settlement_accounts_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE image ADD CONSTRAINT FK_C53D045F6D021EF0 FOREIGN KEY (settlement_accounts_id) REFERENCES settlement_accounts (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX idx_image_settlement_accounts ON image (settlement_accounts_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE settlement_accounts DROP CONSTRAINT FK_17D0AAA0166D1F9C');
        $this->addSql('DROP TABLE settlement_accounts');
        $this->addSql('ALTER TABLE file DROP CONSTRAINT FK_8C9F36106D021EF0');
        $this->addSql('DROP INDEX idx_file_settlement_accounts');
        $this->addSql('ALTER TABLE file DROP settlement_accounts_id');
        $this->addSql('ALTER TABLE image DROP CONSTRAINT FK_C53D045F6D021EF0');
        $this->addSql('DROP INDEX idx_image_settlement_accounts');
        $this->addSql('ALTER TABLE image DROP settlement_accounts_id');
    }
}
