<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260629120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add project_task table for per-project task tracking';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE project_task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, project_id INT NOT NULL, assignee_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, responsible_unit VARCHAR(255) DEFAULT NULL, cooperating_unit VARCHAR(255) DEFAULT NULL, start_date DATE DEFAULT NULL, end_date DATE DEFAULT NULL, duration_days INT DEFAULT NULL, progress_text TEXT DEFAULT NULL, status VARCHAR(255) NOT NULL, priority VARCHAR(255) NOT NULL, due_date DATE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_project_task_project ON project_task (project_id)');
        $this->addSql('CREATE INDEX idx_project_task_status ON project_task (status)');
        $this->addSql('CREATE INDEX idx_project_task_assignee ON project_task (assignee_id)');
        $this->addSql('CREATE INDEX idx_project_task_due_date ON project_task (due_date)');
        $this->addSql('CREATE INDEX idx_project_task_start_date ON project_task (start_date)');
        $this->addSql('CREATE INDEX idx_project_task_end_date ON project_task (end_date)');
        $this->addSql('CREATE INDEX IDX_6BEF1330166D1F9C ON project_task (project_id)');
        $this->addSql('CREATE INDEX IDX_6BEF133059EC7BC0 ON project_task (assignee_id)');
        $this->addSql('CREATE INDEX IDX_6BEF1330B03A8386 ON project_task (created_by_id)');
        $this->addSql('ALTER TABLE project_task ADD CONSTRAINT FK_6BEF1330166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_task ADD CONSTRAINT FK_6BEF133059EC7BC0 FOREIGN KEY (assignee_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_task ADD CONSTRAINT FK_6BEF1330B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE project_task DROP CONSTRAINT FK_6BEF1330166D1F9C');
        $this->addSql('ALTER TABLE project_task DROP CONSTRAINT FK_6BEF133059EC7BC0');
        $this->addSql('ALTER TABLE project_task DROP CONSTRAINT FK_6BEF1330B03A8386');
        $this->addSql('DROP TABLE project_task');
    }
}
