<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260205094849 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE project_base (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, project_name VARCHAR(255) NOT NULL, project_number VARCHAR(50) DEFAULT NULL, project_type VARCHAR(255) NOT NULL, project_subtype VARCHAR(100) DEFAULT NULL, project_industry VARCHAR(100) NOT NULL, project_location VARCHAR(255) NOT NULL, project_nature VARCHAR(255) NOT NULL, leader_name VARCHAR(100) NOT NULL, leader_phone VARCHAR(20) NOT NULL, leader_email VARCHAR(255) DEFAULT NULL, budget NUMERIC(15, 2) NOT NULL, planned_start_date DATE NOT NULL, planned_end_date DATE NOT NULL, purpose TEXT NOT NULL, scale TEXT NOT NULL, funding_source VARCHAR(255) NOT NULL, registrant_name VARCHAR(100) NOT NULL, registrant_organization VARCHAR(255) NOT NULL, registrant_phone VARCHAR(20) NOT NULL, remarks TEXT DEFAULT NULL, special_notes TEXT DEFAULT NULL, prerequisite_notes TEXT DEFAULT NULL, status VARCHAR(255) NOT NULL, is_core_locked BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F92536798134F41E ON project_base (project_number)');
        $this->addSql('CREATE INDEX idx_project_number ON project_base (project_number)');
        $this->addSql('CREATE INDEX idx_status ON project_base (status)');
        $this->addSql('CREATE INDEX idx_created_at ON project_base (created_at)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE project_base');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
