<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260206094523 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE completion_acceptance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, acceptance_date DATE DEFAULT NULL, completion_report_details TEXT DEFAULT NULL, quality_evaluation_details TEXT DEFAULT NULL, acceptance_inspection_details TEXT DEFAULT NULL, defect_rectification_details TEXT DEFAULT NULL, final_accounts_details TEXT DEFAULT NULL, archive_documentation_details TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FE058EC5166D1F9C ON completion_acceptance (project_id)');
        $this->addSql('CREATE INDEX idx_completion_acceptance_date ON completion_acceptance (acceptance_date)');
        $this->addSql('CREATE INDEX idx_completion_acceptance_created_at ON completion_acceptance (created_at)');
        $this->addSql('ALTER TABLE completion_acceptance ADD CONSTRAINT FK_FE058EC5166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE file ADD completion_acceptance_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE file ADD CONSTRAINT FK_8C9F3610244FD02F FOREIGN KEY (completion_acceptance_id) REFERENCES completion_acceptance (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX idx_file_completion_acceptance ON file (completion_acceptance_id)');
        $this->addSql('ALTER TABLE image ADD completion_acceptance_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE image ADD CONSTRAINT FK_C53D045F244FD02F FOREIGN KEY (completion_acceptance_id) REFERENCES completion_acceptance (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX idx_image_completion_acceptance ON image (completion_acceptance_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE completion_acceptance DROP CONSTRAINT FK_FE058EC5166D1F9C');
        $this->addSql('DROP TABLE completion_acceptance');
        $this->addSql('ALTER TABLE file DROP CONSTRAINT FK_8C9F3610244FD02F');
        $this->addSql('DROP INDEX idx_file_completion_acceptance');
        $this->addSql('ALTER TABLE file DROP completion_acceptance_id');
        $this->addSql('ALTER TABLE image DROP CONSTRAINT FK_C53D045F244FD02F');
        $this->addSql('DROP INDEX idx_image_completion_acceptance');
        $this->addSql('ALTER TABLE image DROP completion_acceptance_id');
    }
}
