<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260214082505 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE permission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, permission_code VARCHAR(100) NOT NULL, permission_name VARCHAR(100) NOT NULL, permission_description TEXT DEFAULT NULL, module VARCHAR(50) NOT NULL, operation_type VARCHAR(50) NOT NULL, permission_level INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, parent_permission_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E04992AA26DBAB38 ON permission (permission_code)');
        $this->addSql('CREATE INDEX IDX_E04992AA225F6F58 ON permission (parent_permission_id)');
        $this->addSql('CREATE INDEX idx_permission_code ON permission (permission_code)');
        $this->addSql('CREATE INDEX idx_module ON permission (module)');
        $this->addSql('CREATE TABLE role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role_code VARCHAR(50) NOT NULL, role_name VARCHAR(100) NOT NULL, role_description TEXT DEFAULT NULL, is_preset BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_57698A6AC9AA420C ON role (role_code)');
        $this->addSql('CREATE INDEX idx_role_code ON role (role_code)');
        $this->addSql('CREATE TABLE role_permission (role_id INT NOT NULL, permission_id INT NOT NULL, PRIMARY KEY (role_id, permission_id))');
        $this->addSql('CREATE INDEX IDX_6F7DF886D60322AC ON role_permission (role_id)');
        $this->addSql('CREATE INDEX IDX_6F7DF886FED90CCA ON role_permission (permission_id)');
        $this->addSql('CREATE TABLE user_role (user_id INT NOT NULL, role_id INT NOT NULL, PRIMARY KEY (user_id, role_id))');
        $this->addSql('CREATE INDEX IDX_2DE8C6A3A76ED395 ON user_role (user_id)');
        $this->addSql('CREATE INDEX IDX_2DE8C6A3D60322AC ON user_role (role_id)');
        $this->addSql('ALTER TABLE permission ADD CONSTRAINT FK_E04992AA225F6F58 FOREIGN KEY (parent_permission_id) REFERENCES permission (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE role_permission ADD CONSTRAINT FK_6F7DF886D60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE role_permission ADD CONSTRAINT FK_6F7DF886FED90CCA FOREIGN KEY (permission_id) REFERENCES permission (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_role ADD CONSTRAINT FK_2DE8C6A3A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_role ADD CONSTRAINT FK_2DE8C6A3D60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE org ADD org_code VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE org ADD description TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE org ADD contact_person VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE org ADD contact_phone VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE org ADD address VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE org ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE org ALTER name TYPE VARCHAR(255)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7215BA80EEFD2400 ON org (org_code)');
        $this->addSql('ALTER TABLE project ADD org_id INT NOT NULL');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EEF4837C1B FOREIGN KEY (org_id) REFERENCES org (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('CREATE INDEX idx_project_org ON project (org_id)');
        $this->addSql('ALTER TABLE "user" ADD phone VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD email VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD position VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD is_active BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD last_login_ip VARCHAR(45) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD org_id INT NOT NULL');
        $this->addSql('ALTER TABLE "user" ALTER name TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE "user" ALTER name SET NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649F4837C1B FOREIGN KEY (org_id) REFERENCES org (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('CREATE INDEX idx_user_org ON "user" (org_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE permission DROP CONSTRAINT FK_E04992AA225F6F58');
        $this->addSql('ALTER TABLE role_permission DROP CONSTRAINT FK_6F7DF886D60322AC');
        $this->addSql('ALTER TABLE role_permission DROP CONSTRAINT FK_6F7DF886FED90CCA');
        $this->addSql('ALTER TABLE user_role DROP CONSTRAINT FK_2DE8C6A3A76ED395');
        $this->addSql('ALTER TABLE user_role DROP CONSTRAINT FK_2DE8C6A3D60322AC');
        $this->addSql('DROP TABLE permission');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE role_permission');
        $this->addSql('DROP TABLE user_role');
        $this->addSql('DROP INDEX UNIQ_7215BA80EEFD2400');
        $this->addSql('ALTER TABLE org DROP org_code');
        $this->addSql('ALTER TABLE org DROP description');
        $this->addSql('ALTER TABLE org DROP contact_person');
        $this->addSql('ALTER TABLE org DROP contact_phone');
        $this->addSql('ALTER TABLE org DROP address');
        $this->addSql('ALTER TABLE org DROP updated_at');
        $this->addSql('ALTER TABLE org ALTER name TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE project DROP CONSTRAINT FK_2FB3D0EEF4837C1B');
        $this->addSql('DROP INDEX idx_project_org');
        $this->addSql('ALTER TABLE project DROP org_id');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649F4837C1B');
        $this->addSql('DROP INDEX idx_user_org');
        $this->addSql('ALTER TABLE "user" DROP phone');
        $this->addSql('ALTER TABLE "user" DROP email');
        $this->addSql('ALTER TABLE "user" DROP position');
        $this->addSql('ALTER TABLE "user" DROP is_active');
        $this->addSql('ALTER TABLE "user" DROP last_login_at');
        $this->addSql('ALTER TABLE "user" DROP last_login_ip');
        $this->addSql('ALTER TABLE "user" DROP created_at');
        $this->addSql('ALTER TABLE "user" DROP updated_at');
        $this->addSql('ALTER TABLE "user" DROP org_id');
        $this->addSql('ALTER TABLE "user" ALTER name TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE "user" ALTER name DROP NOT NULL');
    }
}
