<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260206090230 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create ProjectApproval entity (立项流程) and add relationships with File/Image entities';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE project_approval (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date DATE DEFAULT NULL, completion_date DATE DEFAULT NULL, approving_authority VARCHAR(255) DEFAULT NULL, approval_document_number VARCHAR(100) DEFAULT NULL, investment_approval_details TEXT DEFAULT NULL, land_use_approval_details TEXT DEFAULT NULL, environmental_assessment_details TEXT DEFAULT NULL, social_stability_assessment_details TEXT DEFAULT NULL, approval_opinions TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2BAE1EF0166D1F9C ON project_approval (project_id)');
        $this->addSql('ALTER TABLE project_approval ADD CONSTRAINT FK_2BAE1EF0166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE file ADD project_approval_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE file ADD CONSTRAINT FK_8C9F361036AA07FB FOREIGN KEY (project_approval_id) REFERENCES project_approval (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX idx_file_project_approval ON file (project_approval_id)');
        $this->addSql('ALTER TABLE image ADD project_approval_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE image ADD CONSTRAINT FK_C53D045F36AA07FB FOREIGN KEY (project_approval_id) REFERENCES project_approval (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX idx_image_project_approval ON image (project_approval_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE project_approval DROP CONSTRAINT FK_2BAE1EF0166D1F9C');
        $this->addSql('DROP TABLE project_approval');
        $this->addSql('ALTER TABLE file DROP CONSTRAINT FK_8C9F361036AA07FB');
        $this->addSql('DROP INDEX idx_file_project_approval');
        $this->addSql('ALTER TABLE file DROP project_approval_id');
        $this->addSql('ALTER TABLE image DROP CONSTRAINT FK_C53D045F36AA07FB');
        $this->addSql('DROP INDEX idx_image_project_approval');
        $this->addSql('ALTER TABLE image DROP project_approval_id');
    }
}
