<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260206092700 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create ConstructionPreparation entity (施工准备流程) and add relationships with File/Image entities';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE construction_preparation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date DATE DEFAULT NULL, completion_date DATE DEFAULT NULL, construction_unit VARCHAR(255) DEFAULT NULL, construction_permit_number VARCHAR(100) DEFAULT NULL, bid_details TEXT DEFAULT NULL, contract_details TEXT DEFAULT NULL, construction_plan_details TEXT DEFAULT NULL, quality_control_details TEXT DEFAULT NULL, safety_plan_details TEXT DEFAULT NULL, environmental_protection_details TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C52DEC80166D1F9C ON construction_preparation (project_id)');
        $this->addSql('ALTER TABLE construction_preparation ADD CONSTRAINT FK_C52DEC80166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE file ADD construction_preparation_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE file ADD CONSTRAINT FK_8C9F361030603EE0 FOREIGN KEY (construction_preparation_id) REFERENCES construction_preparation (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX idx_file_construction_preparation ON file (construction_preparation_id)');
        $this->addSql('ALTER TABLE image ADD construction_preparation_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE image ADD CONSTRAINT FK_C53D045F30603EE0 FOREIGN KEY (construction_preparation_id) REFERENCES construction_preparation (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX idx_image_construction_preparation ON image (construction_preparation_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE construction_preparation DROP CONSTRAINT FK_C52DEC80166D1F9C');
        $this->addSql('DROP TABLE construction_preparation');
        $this->addSql('ALTER TABLE file DROP CONSTRAINT FK_8C9F361030603EE0');
        $this->addSql('DROP INDEX idx_file_construction_preparation');
        $this->addSql('ALTER TABLE file DROP construction_preparation_id');
        $this->addSql('ALTER TABLE image DROP CONSTRAINT FK_C53D045F30603EE0');
        $this->addSql('DROP INDEX idx_image_construction_preparation');
        $this->addSql('ALTER TABLE image DROP construction_preparation_id');
    }
}
