<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260206091336 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create PlanningDesign entity (规划设计流程) and add relationships with File/Image entities';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE planning_design (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date DATE DEFAULT NULL, completion_date DATE DEFAULT NULL, design_unit VARCHAR(255) DEFAULT NULL, design_document_number VARCHAR(100) DEFAULT NULL, preliminary_design_details TEXT DEFAULT NULL, technical_design_details TEXT DEFAULT NULL, construction_drawing_details TEXT DEFAULT NULL, budget_estimate_details TEXT DEFAULT NULL, design_review_details TEXT DEFAULT NULL, design_approval_details TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AD6E785F166D1F9C ON planning_design (project_id)');
        $this->addSql('ALTER TABLE planning_design ADD CONSTRAINT FK_AD6E785F166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE file ADD planning_design_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE file ADD CONSTRAINT FK_8C9F36104C4D13B1 FOREIGN KEY (planning_design_id) REFERENCES planning_design (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX idx_file_planning_design ON file (planning_design_id)');
        $this->addSql('ALTER TABLE image ADD planning_design_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE image ADD CONSTRAINT FK_C53D045F4C4D13B1 FOREIGN KEY (planning_design_id) REFERENCES planning_design (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX idx_image_planning_design ON image (planning_design_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE planning_design DROP CONSTRAINT FK_AD6E785F166D1F9C');
        $this->addSql('DROP TABLE planning_design');
        $this->addSql('ALTER TABLE file DROP CONSTRAINT FK_8C9F36104C4D13B1');
        $this->addSql('DROP INDEX idx_file_planning_design');
        $this->addSql('ALTER TABLE file DROP planning_design_id');
        $this->addSql('ALTER TABLE image DROP CONSTRAINT FK_C53D045F4C4D13B1');
        $this->addSql('DROP INDEX idx_image_planning_design');
        $this->addSql('ALTER TABLE image DROP planning_design_id');
    }
}
