<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260206021024 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Convert ProjectType and ProjectSubtype from enum/string to entities';
    }

    public function up(Schema $schema): void
    {
        // Create project_type and project_subtype tables
        $this->addSql('CREATE TABLE project_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, sort_order INT NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B54F9F3177153098 ON project_type (code)');
        $this->addSql('CREATE INDEX idx_project_type_code ON project_type (code)');
        $this->addSql('CREATE INDEX idx_project_type_active ON project_type (is_active)');

        $this->addSql('CREATE TABLE project_subtype (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, sort_order INT NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_type_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C37529C777153098 ON project_subtype (code)');
        $this->addSql('CREATE INDEX IDX_C37529C7535280F6 ON project_subtype (project_type_id)');
        $this->addSql('CREATE INDEX idx_project_subtype_code ON project_subtype (code)');
        $this->addSql('CREATE INDEX idx_project_subtype_active ON project_subtype (is_active)');
        $this->addSql('ALTER TABLE project_subtype ADD CONSTRAINT FK_C37529C7535280F6 FOREIGN KEY (project_type_id) REFERENCES project_type (id) ON DELETE CASCADE NOT DEFERRABLE');

        // Add new foreign key columns to project table (nullable initially)
        $this->addSql('ALTER TABLE project ADD project_type_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE project ADD project_subtype_id INT DEFAULT NULL');

        // Note: Data migration will be done via fixtures - load them with:
        // bin/console doctrine:fixtures:load --purge-with-truncate

        // After data migration, make project_type_id NOT NULL
        // This will be done manually: ALTER TABLE project ALTER COLUMN project_type_id SET NOT NULL;

        // Drop old columns (do this after data migration)
        // $this->addSql('ALTER TABLE project DROP project_type');
        // $this->addSql('ALTER TABLE project DROP project_subtype');

        // Add foreign key constraints
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE535280F6 FOREIGN KEY (project_type_id) REFERENCES project_type (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE96885F6E FOREIGN KEY (project_subtype_id) REFERENCES project_subtype (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_2FB3D0EE535280F6 ON project (project_type_id)');
        $this->addSql('CREATE INDEX IDX_2FB3D0EE96885F6E ON project (project_subtype_id)');
        $this->addSql('ALTER INDEX uniq_f92536798134f41e RENAME TO UNIQ_2FB3D0EE8134F41E');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE project_subtype DROP CONSTRAINT FK_C37529C7535280F6');
        $this->addSql('DROP TABLE project_subtype');
        $this->addSql('DROP TABLE project_type');
        $this->addSql('ALTER TABLE project DROP CONSTRAINT FK_2FB3D0EE535280F6');
        $this->addSql('ALTER TABLE project DROP CONSTRAINT FK_2FB3D0EE96885F6E');
        $this->addSql('DROP INDEX IDX_2FB3D0EE535280F6');
        $this->addSql('DROP INDEX IDX_2FB3D0EE96885F6E');
        $this->addSql('ALTER TABLE project ADD project_type VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE project ADD project_subtype VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE project DROP project_type_id');
        $this->addSql('ALTER TABLE project DROP project_subtype_id');
        $this->addSql('ALTER INDEX uniq_2fb3d0ee8134f41e RENAME TO uniq_f92536798134f41e');
    }
}
