<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260206084927 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create PreliminaryDecision entity and move preliminary decision fields from Project to separate table';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs

        // Create preliminary_decision table
        $this->addSql('CREATE TABLE preliminary_decision (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date DATE DEFAULT NULL, completion_date DATE DEFAULT NULL, organizing_unit VARCHAR(255) DEFAULT NULL, project_proposal_details TEXT DEFAULT NULL, feasibility_study_details TEXT DEFAULT NULL, feasibility_study_organization VARCHAR(255) DEFAULT NULL, funding_arrangement_details TEXT DEFAULT NULL, approval_opinions TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F6B5692A166D1F9C ON preliminary_decision (project_id)');
        $this->addSql('ALTER TABLE preliminary_decision ADD CONSTRAINT FK_F6B5692A166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE');

        // Add preliminary_decision_id to file table
        $this->addSql('ALTER TABLE file ADD preliminary_decision_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE file ADD CONSTRAINT FK_8C9F36105CAF911D FOREIGN KEY (preliminary_decision_id) REFERENCES preliminary_decision (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX idx_file_preliminary_decision ON file (preliminary_decision_id)');

        // Remove project_id from file table (replaced by preliminary_decision relationship)
        $this->addSql('ALTER TABLE file DROP CONSTRAINT IF EXISTS FK_8C9F3610166D1F9C');
        $this->addSql('DROP INDEX IF EXISTS idx_file_project');
        $this->addSql('ALTER TABLE file DROP COLUMN IF EXISTS project_id');

        // Add preliminary_decision_id to image table
        $this->addSql('ALTER TABLE image ADD preliminary_decision_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE image ADD CONSTRAINT FK_C53D045F5CAF911D FOREIGN KEY (preliminary_decision_id) REFERENCES preliminary_decision (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX idx_image_preliminary_decision ON image (preliminary_decision_id)');

        // Remove project_id from image table (replaced by preliminary_decision relationship)
        $this->addSql('ALTER TABLE image DROP CONSTRAINT IF EXISTS FK_C53D045F166D1F9C');
        $this->addSql('DROP INDEX IF EXISTS idx_image_project');
        $this->addSql('ALTER TABLE image DROP COLUMN IF EXISTS project_id');

        // Remove old preliminary decision fields from project table
        $this->addSql('ALTER TABLE project DROP COLUMN IF EXISTS preliminary_decision_start_date');
        $this->addSql('ALTER TABLE project DROP COLUMN IF EXISTS preliminary_decision_completion_date');
        $this->addSql('ALTER TABLE project DROP COLUMN IF EXISTS organizing_unit');
        $this->addSql('ALTER TABLE project DROP COLUMN IF EXISTS project_proposal_details');
        $this->addSql('ALTER TABLE project DROP COLUMN IF EXISTS feasibility_study_details');
        $this->addSql('ALTER TABLE project DROP COLUMN IF EXISTS feasibility_study_organization');
        $this->addSql('ALTER TABLE project DROP COLUMN IF EXISTS funding_arrangement_details');
        $this->addSql('ALTER TABLE project DROP COLUMN IF EXISTS approval_opinions');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs

        // Restore preliminary decision fields to project table
        $this->addSql('ALTER TABLE project ADD preliminary_decision_start_date DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE project ADD preliminary_decision_completion_date DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE project ADD organizing_unit VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE project ADD project_proposal_details TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE project ADD feasibility_study_details TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE project ADD feasibility_study_organization VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE project ADD funding_arrangement_details TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE project ADD approval_opinions TEXT DEFAULT NULL');

        // Restore project_id to file and image tables
        $this->addSql('ALTER TABLE file ADD project_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE file ADD CONSTRAINT FK_8C9F3610166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX idx_file_project ON file (project_id)');

        $this->addSql('ALTER TABLE image ADD project_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE image ADD CONSTRAINT FK_C53D045F166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX idx_image_project ON image (project_id)');

        // Drop preliminary_decision relationships
        $this->addSql('ALTER TABLE file DROP CONSTRAINT FK_8C9F36105CAF911D');
        $this->addSql('DROP INDEX idx_file_preliminary_decision');
        $this->addSql('ALTER TABLE file DROP preliminary_decision_id');

        $this->addSql('ALTER TABLE image DROP CONSTRAINT FK_C53D045F5CAF911D');
        $this->addSql('DROP INDEX idx_image_preliminary_decision');
        $this->addSql('ALTER TABLE image DROP preliminary_decision_id');

        // Drop preliminary_decision table
        $this->addSql('ALTER TABLE preliminary_decision DROP CONSTRAINT FK_F6B5692A166D1F9C');
        $this->addSql('DROP TABLE preliminary_decision');
    }
}
